version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: ddc_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ddc_dev

  redis:
    image: redis:7-alpine
    container_name: ddc_redis
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
