import mongoose from 'mongoose';
import { Payout, type IPayout } from './payout.model.js';
import { Invoice } from '../invoicing/invoice.model.js';
import { Order } from '../orders/order.model.js';
import { Store } from '../stores/store.model.js';
import { AppError } from '../../lib/errors.js';
import { logger } from '../../lib/logger.js';
import {
  PayoutStatus, InvoiceStatus, PaymentMode, OrderStatus,
} from '@ddc/shared';

// ── Run a payout settlement for one store ─────────────────────────────────────
//
// Collects all COMPLETED orders with PAID invoices that have not yet been
// included in a payout for the given period. Calculates:
//  - totalInvoicedPaise: sum of all invoice totals
//  - totalCommissionPaise: platform commission at store's commissionPercent
//  - onlineSharePaise: for ONLINE orders (gateway already split, so this is informational)
//  - codReceivablePaise: commission owed by store for COD orders (cash collected by store)
//  - netPayoutPaise: what the platform sends to the store (ONLINE store share already transferred;
//    for COD the store keeps cash and owes commission back — netted in next payout)

export async function runSettlement(
  storeId: string,
  periodFrom: Date,
  periodTo: Date,
  adminId: string,
): Promise<IPayout> {
  const store = await Store.findById(storeId);
  if (!store) throw AppError.notFound('Store', storeId);

  // Check for duplicate period
  const existing = await Payout.findOne({
    storeId,
    periodFrom: { $lte: periodTo },
    periodTo:   { $gte: periodFrom },
    status:     { $ne: PayoutStatus.FAILED },
  });
  if (existing) {
    throw new AppError(409, 'PERIOD_OVERLAP', `A payout already exists overlapping this period (${existing._id}).`);
  }

  const commissionPct = store.commissionPercent / 100;

  // Find all COMPLETED orders in period not yet in a payout
  const existingPayouts = await Payout.find({ storeId }).select('lines.orderId').lean();
  const settledOrderIds = new Set(
    existingPayouts.flatMap(p => p.lines.map(l => l.orderId.toString())),
  );

  const orders = await Order.find({
    storeId,
    status: OrderStatus.COMPLETED,
    paymentStatus: 'PAID',
    createdAt: { $gte: periodFrom, $lte: periodTo },
  }).lean();

  const unsettledOrders = orders.filter(o => !settledOrderIds.has(o._id.toString()));

  if (unsettledOrders.length === 0) {
    throw new AppError(400, 'NO_ORDERS', 'No unsettled completed orders found in this period.');
  }

  // Build payout lines
  let totalInvoiced  = 0;
  let totalCommission = 0;
  let onlineShare    = 0;
  let codReceivable  = 0;

  const lines = await Promise.all(
    unsettledOrders.map(async (order) => {
      const invoice = await Invoice.findOne({
        orderId: order._id,
        status:  InvoiceStatus.PAID,
      }).lean();

      const invoiceTotal = invoice?.totalPaise ?? order.estimatePaise - order.discountPaise;
      const commission   = Math.round(invoiceTotal * commissionPct);
      const storeShare   = invoiceTotal - commission;

      totalInvoiced   += invoiceTotal;
      totalCommission += commission;

      if (order.paymentMode === PaymentMode.ONLINE) {
        onlineShare += storeShare;
      } else {
        // COD: store has cash; commission is a receivable
        codReceivable += commission;
      }

      return {
        orderId:           order._id,
        orderRef:          order.orderRef,
        invoiceRef:        invoice?.invoiceRef ?? 'N/A',
        invoiceTotalPaise: invoiceTotal,
        commissionPaise:   commission,
        storeSharePaise:   storeShare,
        paymentMode:       order.paymentMode,
        completedAt:       order.updatedAt,
      };
    }),
  );

  // For ONLINE orders the gateway already split — store already received their share.
  // netPayoutPaise represents any additional manual transfer needed (usually 0 for auto-split).
  // For COD the store owes commission back — shown as a negative adjustment for clarity.
  const netPayout = onlineShare; // online share already routed; COD handled separately

  const payout = await Payout.create({
    storeId,
    periodFrom,
    periodTo,
    status:               PayoutStatus.DRAFT,
    lines,
    totalInvoicedPaise:   totalInvoiced,
    totalCommissionPaise: totalCommission,
    onlineSharePaise:     onlineShare,
    codReceivablePaise:   codReceivable,
    netPayoutPaise:       netPayout,
    notes: `Generated by admin ${adminId}`,
  });

  logger.info({ payoutId: payout._id, storeId, lines: lines.length }, 'Settlement run complete');
  return payout;
}

// ── Admin: approve a payout ───────────────────────────────────────────────────

export async function approvePayout(payoutId: string, adminId: string): Promise<IPayout> {
  const payout = await Payout.findById(payoutId);
  if (!payout) throw AppError.notFound('Payout', payoutId);
  if (payout.status !== PayoutStatus.DRAFT) {
    throw new AppError(400, 'WRONG_STATUS', `Cannot approve a payout in status ${payout.status}.`);
  }
  payout.status     = PayoutStatus.APPROVED;
  payout.approvedBy = new mongoose.Types.ObjectId(adminId);
  payout.approvedAt = new Date();
  await payout.save();
  logger.info({ payoutId, adminId }, 'Payout approved');
  return payout;
}

// ── Admin: mark payout paid (after manual bank transfer / gateway payout) ────

export async function markPayoutPaid(
  payoutId: string,
  adminId:  string,
  payoutRef?: string,
  method?:    string,
): Promise<IPayout> {
  const payout = await Payout.findById(payoutId);
  if (!payout) throw AppError.notFound('Payout', payoutId);
  if (payout.status !== PayoutStatus.APPROVED) {
    throw new AppError(400, 'WRONG_STATUS', `Payout must be in APPROVED status to mark paid; current: ${payout.status}.`);
  }
  payout.status    = PayoutStatus.PAID;
  payout.paidAt    = new Date();
  payout.payoutRef = payoutRef;
  if (method) payout.method = method as IPayout['method'];
  await payout.save();
  logger.info({ payoutId, payoutRef }, 'Payout marked paid');
  return payout;
}

// ── Admin: add adjustment (credit or debit) ───────────────────────────────────

export async function addAdjustment(
  payoutId:    string,
  adminId:     string,
  amount:      number,
  description: string,
): Promise<IPayout> {
  const payout = await Payout.findById(payoutId);
  if (!payout) throw AppError.notFound('Payout', payoutId);
  if ([PayoutStatus.PAID, PayoutStatus.PROCESSING].includes(payout.status)) {
    throw new AppError(400, 'LOCKED', 'Cannot adjust a payout that is already paid or processing.');
  }
  payout.adjustments.push({
    amount,
    description,
    by: new mongoose.Types.ObjectId(adminId),
    at: new Date(),
  });
  // Recalculate net
  const adjTotal = payout.adjustments.reduce((s, a) => s + a.amount, 0);
  payout.netPayoutPaise = payout.onlineSharePaise + adjTotal;
  await payout.save();
  return payout;
}

// ── List payouts ──────────────────────────────────────────────────────────────

export async function listPayouts(query: {
  storeId?: string;
  status?:  string;
  from?:    Date;
  to?:      Date;
  page?:    number;
  limit?:   number;
}) {
  const filter: Record<string, unknown> = {};
  if (query.storeId) filter['storeId'] = query.storeId;
  if (query.status)  filter['status']  = query.status;
  if (query.from || query.to) {
    filter['periodFrom'] = {};
    if (query.from) (filter['periodFrom'] as Record<string, unknown>)['$gte'] = query.from;
    if (query.to)   (filter['periodFrom'] as Record<string, unknown>)['$lte'] = query.to;
  }
  const page  = query.page  ?? 1;
  const limit = query.limit ?? 20;
  const skip  = (page - 1) * limit;

  const [payouts, total] = await Promise.all([
    Payout.find(filter).sort({ createdAt: -1 }).skip(skip).limit(limit).lean(),
    Payout.countDocuments(filter),
  ]);

  return { payouts, total, pages: Math.ceil(total / limit), page };
}
